FROM node:22-alpine AS build
LABEL name = "hiver93"
LABEL email = "kdw3238@naver.com"

WORKDIR /app

ENV NODE_ENV=development
COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:22-alpine

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY package.json ./

ENV PORT=5173
EXPOSE 5173

RUN npm install -g serve

CMD ["serve", "-s", "dist", "-l", "5173"]
